import Logger from '../utils/logger';
import UserService from '../services/user.service';
import StoreService from '../services/store.service';
import { IStore } from './models/Store';
import { IUser } from './models/User';

// Total 50 Stores
const stores: IStore[] = [
  {
    name: 'La gran tienda',
    cuit: '33-52652082-9',
    concepts: ['Juegos', 'Viajes', 'Panaderia', 'Transporte', 'Turismo', 'Ferreteria'],
    currentBalance: 300,
    active: true,
    lastSale: new Date('2022-4-20'),
  },
  {
    name: 'La mejor tienda',
    cuit: '33-526520345-2',
    concepts: ['Construccion', 'miscelanea', 'Electricidad'],
    currentBalance: 1000,
    active: true,
    lastSale: new Date('2022-6-20'),
  },
  {
    name: 'La tienda verde',
    cuit: '33-28652282-9',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 600,
    active: false,
    lastSale: new Date('2020-4-10'),
  },
  {
    name: 'La llorona',
    cuit: '33-28652282-9',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 600,
    active: false,
    lastSale: new Date('2020-4-10'),
  },
  {
    name: 'Panaderia fresca',
    cuit: '32-28772282-3',
    concepts: ['Pasteleria', 'Panaderia', 'Distribuidor', 'Cafeteria', 'Restaurante'],
    currentBalance: 850,
    active: true,
    lastSale: new Date('2022-8-15'),
  },
  {
    name: 'La Regata',
    cuit: '31-28652569-8',
    concepts: ['Restaurante', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 1500,
    active: true,
    lastSale: new Date('2022-7-21'),
  },
  {
    name: 'Constructora Azul',
    cuit: '31-28652190-9',
    concepts: ['Constructora', 'Naviera', 'Ingenieria', 'Cantera'],
    currentBalance: 6500,
    active: true,
    lastSale: new Date('2022-4-5'),
  },
  {
    name: 'ingeniarte',
    cuit: '33-26282082-3',
    concepts: ['Papeleria', 'Miscelanea', 'Confiteria', 'Comida rapida', 'Plotter', 'Impresiones'],
    currentBalance: 1200,
    active: true,
    lastSale: new Date('2022-5-30'),
  },
  {
    name: 'San Benito',
    cuit: '32-35402081-7',
    concepts: ['Hospital', 'Salud', 'Cuidades integrales'],
    currentBalance: 55400,
    active: true,
    lastSale: new Date('2022-7-10'),
  },
  {
    name: 'Rosado suave',
    cuit: '30-35402081-9',
    concepts: ['Belleza', 'Salud', 'Spa', 'Estetica', 'Peluqueria', 'Cosmetologia'],
    currentBalance: 500,
    active: true,
    lastSale: new Date('2022-3-15'),
  },
  {
    name: 'Magdalena',
    cuit: '33-28652564-6',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Restaurante', 'Turismo', 'Comidas rapidas'],
    currentBalance: 650,
    active: true,
    lastSale: new Date('2022-2-11'),
  },
  {
    name: 'Pan Dorado',
    cuit: '32-28775555-5',
    concepts: ['Pasteleria', 'Panaderia', 'Cafeteria'],
    currentBalance: 770,
    active: true,
    lastSale: new Date('2022-7-25'),
  },
  {
    name: 'El otro camino',
    cuit: '34-22282082-2',
    concepts: ['Juegos', 'Viajes', 'Diversion', 'Transporte', 'Turismo', 'Entretenimiento'],
    currentBalance: 900,
    active: true,
    lastSale: new Date('2022-5-21'),
  },
  {
    name: 'Construsas',
    cuit: '30-526520345-0',
    concepts: ['Construccion', 'miscelanea', 'Electricidad', 'Herramientas', 'Distribuidor', 'Cantera'],
    currentBalance: 5200,
    active: true,
    lastSale: new Date('2022-2-30'),
  },
  {
    name: 'Amanecer',
    cuit: '20-28652111-6',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno'],
    currentBalance: 400,
    active: true,
    lastSale: new Date('2022-4-21'),
  },
  {
    name: 'Crearte',
    cuit: '33-26223452-2',
    concepts: ['Papeleria', 'Miscelanea', 'Confiteria', 'Pasabocas', 'Plotter', 'Impresiones'],
    currentBalance: 800,
    active: false,
    lastSale: new Date('2019-5-14'),
  },
  {
    name: 'Sanarte',
    cuit: '32-35333331-7',
    concepts: ['Hospital', 'Salud', 'Cuidades integrales', 'Funeraria', 'Hospitalizacion'],
    currentBalance: 332400,
    active: true,
    lastSale: new Date('2022-7-30'),
  },
  {
    name: 'Actualizate',
    cuit: '35-55552081-6',
    concepts: ['Belleza', 'Salud', 'Spa', 'Estetica', 'Peluqueria', 'Cosmetologia'],
    currentBalance: 800,
    active: false,
    lastSale: new Date('2018-2-18'),
  },
  {
    name: 'La base',
    cuit: '33-28644476-7',
    concepts: ['Entretenimiento', 'Cocteleria', 'Club nocturno', 'Club de danza'],
    currentBalance: 400,
    active: true,
    lastSale: new Date('2020-5-25'),
  },
  {
    name: 'El dorado',
    cuit: '33-55522282-1',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Restaurante', 'Comidas rapidas'],
    currentBalance: 800,
    active: true,
    lastSale: new Date('2022-3-20'),
  },
  {
    name: 'Panaderia linda',
    cuit: '34-28744282-4',
    concepts: ['Pasteleria', 'Panaderia', 'Comida rapida', 'Cafeteria'],
    currentBalance: 850,
    active: false,
    lastSale: new Date('2021-1-15'),
  },
  {
    name: 'La azucarada',
    cuit: '31-28699999-9',
    concepts: ['Restaurante', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 2200,
    active: false,
    lastSale: new Date('2018-4-2'),
  },
  {
    name: 'La Regata',
    cuit: '31-28652569-8',
    concepts: ['Restaurante', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 1500,
    active: true,
    lastSale: new Date('2022-7-21'),
  },
  {
    name: 'ConstructoraBlanco',
    cuit: '31-2861111111',
    concepts: ['Constructora', 'Naviera', 'Ingenieria', 'Cantera', 'Renovaciones', 'Conservacion'],
    currentBalance: 2230,
    active: true,
    lastSale: new Date('2022-3-3'),
  },
  {
    name: 'Dibujos y letras',
    cuit: '33-26282044-3',
    concepts: ['Papeleria', 'Miscelanea', 'Confiteria', 'Manualidades', 'Plotter', 'Impresiones'],
    currentBalance: 1200,
    active: true,
    lastSale: new Date('2022-4-1'),
  },
  {
    name: 'tienda roja',
    cuit: '33-52652082-9',
    concepts: ['Juegos', 'Viajes', 'Transporte', 'Turismo'],
    currentBalance: 8200,
    active: true,
    lastSale: new Date('2022-5-20'),
  },
  {
    name: 'construitan',
    cuit: '23-526520322-2',
    concepts: ['Construccion', 'miscelanea', 'Electricidad'],
    currentBalance: 3000,
    active: true,
    lastSale: new Date('2022-5-10'),
  },
  {
    name: 'El comienzo',
    cuit: '30-28652280-0',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno'],
    currentBalance: 990,
    active: true,
    lastSale: new Date('2020-6-18'),
  },
  {
    name: 'Tentacion',
    cuit: '33-28652282-3',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 900,
    active: false,
    lastSale: new Date('2012-3-13'),
  },
  {
    name: 'Paniexpress',
    cuit: '32-28773333-3',
    concepts: ['Pasteleria', 'Panaderia', 'Distribuidor', 'Cafeteria', 'Restaurante'],
    currentBalance: 250,
    active: true,
    lastSale: new Date('2022-9-10'),
  },
  {
    name: 'Delicias norteñas',
    cuit: '31-28658888-8',
    concepts: ['Restaurante', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo'],
    currentBalance: 2200,
    active: false,
    lastSale: new Date('2018-7-22'),
  },
  {
    name: 'Servicostru',
    cuit: '31-11111990-1',
    concepts: ['Constructora', 'Naviera', 'Ingenieria', 'Cantera'],
    currentBalance: 900,
    active: true,
    lastSale: new Date('2022-4-9'),
  },
  {
    name: 'sinon',
    cuit: '33-11182082-3',
    concepts: ['Papeleria', 'Miscelanea', 'Confiteria', 'Comida rapida', 'Plotter', 'Impresiones'],
    currentBalance: 6600,
    active: false,
    lastSale: new Date('2018-5-3'),
  },
  {
    name: 'Hospital verde',
    cuit: '32-35402077-7',
    concepts: ['Hospital', 'Salud', 'Cuidades integrales', 'Hospitalizacion', 'Cuidados prenatales'],
    currentBalance: 550,
    active: true,
    lastSale: new Date('2022-5-13'),
  },
  {
    name: 'Estetica provincia',
    cuit: '30-35402777-7',
    concepts: ['Belleza', 'Salud', 'Spa', 'Estetica', 'Peluqueria'],
    currentBalance: 5200,
    active: true,
    lastSale: new Date('2022-3-13'),
  },
  {
    name: 'Magma',
    cuit: '31-28656666-6',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Restaurante', 'Turismo', 'Comidas rapidas'],
    currentBalance: 1550,
    active: true,
    lastSale: new Date('2022-8-21'),
  },
  {
    name: 'Panaderia san barnardino',
    cuit: '32-287733333-0',
    concepts: ['Pasteleria', 'Panaderia', 'Cafeteria'],
    currentBalance: 440,
    active: true,
    lastSale: new Date('2022-7-7'),
  },
  {
    name: 'Diversity',
    cuit: '32-22282666-6',
    concepts: ['Juegos', 'Viajes', 'Diversion', 'Transporte', 'Turismo', 'Entretenimiento'],
    currentBalance: 6600,
    active: true,
    lastSale: new Date('2022-6-26'),
  },
  {
    name: 'Yopal inversiones',
    cuit: '33-526520300-0',
    concepts: ['Construccion', 'miscelanea', 'Electricidad', 'Herramientas', 'Distribuidor', 'Cantera'],
    currentBalance: 2200,
    active: false,
    lastSale: new Date('2018-2-30'),
  },
  {
    name: 'El portal',
    cuit: '20-28655555-5',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Distribuidor'],
    currentBalance: 800,
    active: true,
    lastSale: new Date('2022-4-28'),
  },
  {
    name: 'Cervantes',
    cuit: '33-26228888-8',
    concepts: ['Papeleria', 'Miscelanea', 'Confiteria', 'Pasabocas', 'Plotter', 'Impresiones'],
    currentBalance: 600,
    active: true,
    lastSale: new Date('2022-5-15'),
  },
  {
    name: 'Hospital Monsalve',
    cuit: '32-35399999-9',
    concepts: ['Hospital', 'Salud', 'Cuidades integrales', 'Funeraria', 'Hospitalizacion'],
    currentBalance: 44400,
    active: true,
    lastSale: new Date('2022-5-3'),
  },
  {
    name: 'Renuevate maria',
    cuit: '35-55566666-6',
    concepts: ['Belleza', 'Salud', 'Spa', 'Estetica', 'Peluqueria'],
    currentBalance: 2500,
    active: true,
    lastSale: new Date('2020-2-16'),
  },
  {
    name: 'La realeza',
    cuit: '33-28688888-8',
    concepts: ['Entretenimiento', 'Cocteleria', 'Club nocturno', 'Club de danza'],
    currentBalance: 900,
    active: true,
    lastSale: new Date('2020-5-2'),
  },
  {
    name: 'El azulejo',
    cuit: '33-33332282-1',
    concepts: ['Licoreria', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Restaurante', 'Comidas rapidas'],
    currentBalance: 300,
    active: true,
    lastSale: new Date('2022-6-24'),
  },
  {
    name: 'Panaderia linda',
    cuit: '34-28744282-4',
    concepts: ['Pasteleria', 'Panaderia', 'Comida rapida', 'Cafeteria'],
    currentBalance: 850,
    active: false,
    lastSale: new Date('2021-1-15'),
  },
  {
    name: 'La azucarada',
    cuit: '31-28699999-9',
    concepts: ['Restaurante', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo', 'Comidas rapidas'],
    currentBalance: 200,
    active: true,
    lastSale: new Date('20224-12'),
  },
  {
    name: 'Delicias verdes',
    cuit: '31-28654444-4',
    concepts: ['Restaurante', 'Entretenimiento', 'Cocteleria', 'Club nocturno', 'Turismo'],
    currentBalance: 530,
    active: false,
    lastSale: new Date('2012-5-30'),
  },
  {
    name: 'Construlucian',
    cuit: '31-286111111-2',
    concepts: ['Constructora', 'Naviera', 'Ingenieria', 'Cantera', 'Renovaciones', 'Conservacion'],
    currentBalance: 230,
    active: true,
    lastSale: new Date('2022-6-23'),
  },
  {
    name: 'Miscelania morena',
    cuit: '33-11182044-8',
    concepts: ['Papeleria', 'Miscelanea', 'Confiteria', 'Manualidades', 'Plotter', 'Impresiones'],
    currentBalance: 2500,
    active: false,
    lastSale: new Date('2021-4-13'),
  },
];

export const createInitialStores = async () => {
  await StoreService.createMultipleStores(stores);

  Logger.info('Stores collection successfully populated');
};

export const createInitialUsers = async () => {
  const user: IUser = {
    username: 'test@koibanx.com',
    password: 'admin1234',
  };
  await UserService.createUser(user);

  Logger.info('Test User created');
};
